# Generated by Django 3.2.6 on 2022-08-25 02:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tim3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('11', 'Tomato'), ('10', 'Basil'), ('9', 'Blueberry'), ('8', 'Graphite'), ('7', 'Peacock'), ('6', 'Tangerine'), ('5', 'Banana'), ('4', 'Flamingo'), ('3', 'Grape'), ('2', 'Sage'), ('1', 'Lavender')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_between_events', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('gcal_api_token', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('color', models.CharField(choices=[('11', 'Tomato'), ('10', 'Basil'), ('9', 'Blueberry'), ('8', 'Graphite'), ('7', 'Peacock'), ('6', 'Tangerine'), ('5', 'Banana'), ('4', 'Flamingo'), ('3', 'Grape'), ('2', 'Sage'), ('1', 'Lavender')], max_length=2)),
                ('days', models.JSONField(default=tim3.models.days)),
                ('within_start', models.TimeField(default=datetime.time(8, 0))),
                ('within_end', models.TimeField(default=datetime.time(18, 0))),
                ('by_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tim3.category')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
